server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://192.168.51.236:3306/piaoniu?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
mybatis:
 mapper-locations: classpath:mapper/*.xml
 type-aliases-package: com.piaoniu.demo.model